# NumPy

[NumPy](http://www.numpy.org/), short for Numerical Python, is the core Python package for numerical computing. The main features of NumPy are:

* $n$-dimensional array object `ndarray`
* Vectorized operations and functions which broadcast across arrays for fast computation

To get started with NumPy, let's adopt the standard convention and import it using the name `np`:

In [1]:
import numpy as np

## NumPy Arrays

The fundamental object provided by the NumPy package is the `ndarray`. We can think of a 1D (1-dimensional) `ndarray` as a list, a 2D (2-dimensional) `ndarray` as a matrix, a 3D (3-dimensional) `ndarray` as a 3-tensor (or a "cube" of numbers), and so on.

### Creating Arrays

The function `np.array` creates a NumPy array from a Python sequence such as a list, a tuple or a list of lists. For example, create a 1D NumPy array from a Python list:

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


Note that when we print a NumPy array it looks a lot like a Python list except that the entries are separated by spaces whereas entries in a Python list are separated by commas:

In [3]:
print([1, 2, 3, 4, 5])

[1, 2, 3, 4, 5]


Note also that a NumPy array is displayed slightly differently when output by a cell (as opposed to being explicitly printed to output by the `print` function):

In [4]:
a

array([1, 2, 3, 4, 5])

Use the built-in function `type` to verify the type:

In [5]:
type(a)

numpy.ndarray

Nested sequences, like a list of lists with the same length, are converted into a 2D NumPy array:

In [6]:
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [7]:
type(M)

numpy.ndarray

Create an $n$-dimensional NumPy array from nested Python lists. For example, the following is a 3D NumPy array:

In [8]:
N = np.array([ [[1, 2], [3, 4]] , [[5, 6], [7, 8]] , [[9, 10], [11, 12]] ])
print(N)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


There are several NumPy functions for [creating arrays](https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation):

| Function | Description |
| ---: | :--- |
| `np.array(a)` | Create $n$-dimensional NumPy array from sequence `a` |
| `np.linspace(a,b,N)` | Create 1D NumPy array with `N` equally spaced values from `a` to `b` (inclusively)|
| `np.arange(a,b,step)` | Create 1D NumPy array with values from `a` to `b` (exclusively) incremented by `step`|
| `np.zeros(N)` | Create 1D NumPy array of zeros of length $N$ |
| `np.zeros((n,m))` | Create 2D NumPy array of zeros with $n$ rows and $m$ columns |
| `np.ones(N)` | Create 1D NumPy array of ones of length $N$ |
| `np.ones((n,m))` | Create 2D NumPy array of ones with $n$ rows and $m$ columns |
| `np.eye(N)` | Create 2D NumPy array with $N$ rows and $N$ columns with ones on the diagonal (ie. the identity matrix of size $N$) |

Create a 1D NumPy array with 11 equally spaced values from 0 to 1:

In [9]:
x = np.linspace(0, 1, 11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 2.5:

In [10]:
y = np.arange(0, 20, 2.5)
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


These are the functions that we'll use most often when creating NumPy arrays. The function `np.linspace` works best when we know the *number of elements* we want in the array, and `np.arange` works best when we know *step size* between values in the array.

Create a 1D NumPy array of zeros of length 5:

In [11]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


Create a 2D NumPy array of zeros with 2 rows and 5 columns (note that the argument is a tuple):

In [12]:
M = np.zeros((2, 5))
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create a 1D NumPy array of ones of length 7:

In [13]:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


Create a 2D NumPy array of ones with 3 rows and 2 columns (note that the argument is a tuple):

In [14]:
N = np.ones((3, 2))
print(N)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Create the identity matrix of size 10:

In [15]:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


When dealing with NumPy array, often a dimension are also called **axis**. The only difference is that while dimensions are numbered starting at 1, axis are numbered starting at 0. So, the first dimension correponds to axis 0, the second dimension to axis 1, and so on.

### Dimension, Shape and Size

We can think of a 1D NumPy array as a list of numbers, a 2D NumPy array as a matrix, a 3D NumPy array as a cube of numbers, and so on. Given a NumPy array, we can find out how many dimensions it has by accessing its `.ndim` attribute. The result is a number telling us how many dimensions it has.

For example, create a 2D NumPy array:

In [16]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
A.ndim

2

The result tells us that `A` has 2 dimensions. The first dimension corresponds to the vertical direction counting the rows and the second dimension corresponds to the horizontal direction counting the columns.

We can find out how many rows and columns `A` has by accessing its `.shape` attribute:

In [18]:
A.shape

(3, 2)

The result is a tuple `(3, 2)` of length 2 which means that `A` is a 2D array with 3 rows and 2 columns.

We can also find out how many entries `A` has in total by accessing its `.size` attribute:

In [19]:
A.size

6

This is the expected result since we know that `A` has 3 rows and 2 columns and therefore 2 $\times$ 3 = 6 total entries.

The attributes `.ndim`, `.shape` and `.size` return the same results of the corresponding functions `np.ndim`, `np.shape` and `np.size` when used with the same argument:

In [20]:
r = np.array([9, 3, 1, 7])
print(r)

[9 3 1 7]


In [21]:
np.ndim(r)

1

In [22]:
np.shape(r)

(4,)

In [23]:
np.size(r)

4

Note that `np.shape(r)` is a tuple with a single entry `(4,)`.

### Array Datatype

NumPy arrays are *homogeneous*: all entries in the array are the same datatype. There are different kinds of datatypes provided by NumPy for different applications but we'll mostly be working with the default integer type `np.int64` and the default float type `np.float64`. These are very similar to the built-in Python datatypes `int` and `float` but with some differences that we won't go into. Check out the NumPy documentation on [numeric datatypes](https://docs.scipy.org/doc/numpy/user/basics.types.html) for more information.

The most important point for now is to know how to determine if a NumPy array contains integers elements or float elements. We can access the datatype of a NumPy array by its `.dtype` attribute. For example, create a 2D NumPy array from a list of lists of integers:

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


We expect the datatype of `A` to be integers and we verify:

In [25]:
A.dtype

dtype('int64')

Most of the other NumPy functions which create arrays use the `np.float64` datatype by default. For example, using `np.linspace`:

In [26]:
u = np.linspace(0, 1, 5)
print(u)

[0.   0.25 0.5  0.75 1.  ]


In [27]:
u.dtype

dtype('float64')

Notice that numbers are printed with a decimal point when the datatype of the NumPy array is any kind of float.

We can explicitly convert or *cast* a NumPy array from one data type to another using the `.astype` method:

In [28]:
u_int = u.astype(np.int64)
print(u_int)

[0 0 0 0 1]


In [29]:
u_int.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a NumPy array.

We can explicitly define the type of the array data when we create it, using the `dtype` keyword argument:

In [30]:
A = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [31]:
print(A)

[[1. 2.]
 [3. 4.]]


## Array Operations

[Arithmetic operators](https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations) including addition `+`, subtraction `-`, multiplication `*`, division `/` and exponentiation `**` are applied to arrays *element-wise*. For addition and substraction, these are the familiar vector operations we see in linear algebra:

In [32]:
v = np.array([1,2,3])
w = np.array([1,0,-1])

In [33]:
print(v + w)

[2 2 2]


In [34]:
print(v - w)

[0 2 4]


In the same way, array multiplication and division are performed element by element:

In [35]:
print(v * w)

[ 1  0 -3]


In [36]:
print(w / v)

[ 1.          0.         -0.33333333]


Notice that the datatype of both `v` and `w` is `numpy.int64` however division `w / v` returns an array with datatype `numpy.float64`.

The exponent operator `**` also acts element by element in the array:

In [37]:
print(v ** 2)

[1 4 9]


Let's see these operations for 2D arrays:

In [38]:
A = np.array([[3,1],[2,-1]])
B = np.array([[2,-2],[5,1]])

In [39]:
print(A + B)

[[ 5 -1]
 [ 7  0]]


In [40]:
print(A - B)

[[ 1  3]
 [-3 -2]]


In [41]:
print(A / B)

[[ 1.5 -0.5]
 [ 0.4 -1. ]]


In [42]:
print(A * B)

[[ 6 -2]
 [10 -1]]


In [43]:
print(A ** 2)

[[9 1]
 [4 1]]


Notice that array multiplication and exponentiation are performed element-wise.

In Python 3.5+, the symbol `@` computes matrix multiplication for NumPy arrays:

In [44]:
A @ B

array([[11, -5],
       [-1, -5]])

[Matrix powers](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_power.html) are performed by the function `numpy.linalg.matrix_power`. It's a long function name and so it's convenient to import it with a shorter name:

In [45]:
from numpy.linalg import matrix_power as mpow

Compute $A^3$:

In [46]:
mpow(A,3)

array([[37,  9],
       [18,  1]])

Equivalently, use the `@` operator to compute $A^3$:

In [47]:
A @ A @ A

array([[37,  9],
       [18,  1]])

Conditional operations between arrays of the same size yield boolean array:

In [48]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0., 4., 1.], [7., 2., 12.]])
print(a > b)

[[ True False  True]
 [False  True False]]


### Broadcasting

We know from linear algebra that we can only add matrices of the same size. [Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) is a set of NumPy rules which relaxes this constraint and allows us to combine a smaller array with a bigger when it makes sense.

For example, suppose we want to create a 1D NumPy array of $y$ values for $x=0.0,0.25,0.5,0.75,1.0$ for the function $y = x^2 + 1$. From what we've seen so far, it makes sense to create `x`, then `x**2` and then add an array of ones `[1. 1. 1. 1. 1.]`:

In [49]:
x = np.array([0, 0.25, 0.5, 0.75, 1.0])
y = x ** 2 + np.array([1, 1, 1, 1, 1])
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


An example of broadcasting in NumPy is the following equivalent operation:

In [50]:
x = np.array([0, 0.25, 0.5, 0.75, 1.0])
y = x ** 2 + 1
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


The number 1 is a scalar and we are adding it to a 1D NumPy array of length 5. The broadcasting rule in this case is to broadcast the scalar value 1 across the larger array. The result is a simpler syntax for a very comman operation.

Let's try another example. What happens when we try to add a 1D NumPy array of length 4 to a 2D NumPy array of size 3 by 4?

In [51]:
u = np.array([1, 2, 3, 4])
print(u)

[1 2 3 4]


In [52]:
A = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
print(A)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [53]:
result = A + u
print(result)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


The 1D NumPy array is broadcast across the 2D array because the length of the first dimension in each array are equal!

Broadcasting can also be used with comparison operators:

In [54]:
a = np.array([1, 2, 3, -1, 2, 0, -3, -1])
print(a > 0)

[ True  True  True False  True False False False]


In [55]:
print(a == -1)

[False False False  True False False False  True]


Broadcasting rules are more complex than in these examples, but we will not discuss them in detail.

## Accessing Arrays

Accessing the entries in an array is called *indexing* and accessing rows and columns (or subarrays) is called *slicing*. See the NumPy documentation for more information about [indexing and slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Slicing

Create a 1D NumPy array:

In [56]:
v = np.linspace(0, 5, 11)
print(v)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Access the entries in a 1D array using the square brackets notation just like a Python list. For example, access the entry at index 3:

In [57]:
v[3]

1.5

Notice that NumPy array indices start at 0 just like Python sequences.

Create a 2D array of integers:

In [58]:
B = np.array([[6, 5, 3, 1, 1], [1, 0, 4, 0, 1], [5, 9, 2, 2, 9]])
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


Access the entries in a 2D array using the square brackets with 2 indices. In particular, access the entry at row index 1 and column index 2:

In [59]:
B[1, 2]

4

Access the top left entry in the array:

In [60]:
B[0, 0]

6

Negative indices work for NumPy arrays as they do for Python sequences. Access the bottom right entry in the array:

In [61]:
B[-1, -1]

9

Access the row at index 2 using the colon `:` syntax:

In [62]:
B[2, :]

array([5, 9, 2, 2, 9])

Access the column at index 3:

In [63]:
B[:, 3]

array([1, 0, 2])

Select the subarray of rows at index 1 and 2, and columns at index 2, 3 and 4:

In [64]:
subB = B[1:3, 2:5]
print(subB)

[[4 0 1]
 [2 2 9]]


Slices of NumPy arrays are again NumPy arrays but possibly of a different dimension:

In [65]:
subB.ndim

2

In [66]:
subB.shape

(2, 3)

In [67]:
type(subB)

numpy.ndarray

The variable `subB` is assigned to a 2D NumPy array of shape 2 by 2.

Let's do the same for the column at index 2:

In [68]:
colB = B[:,2]
print(colB)

[3 4 2]


In [69]:
colB.ndim

1

In [70]:
colB.shape

(3,)

In [71]:
type(colB)

numpy.ndarray

The variable `colB` is assigned to a 1D NumPy array of length 3.

One important distinction from Python's lists is that array slices are *views* on the original array. This means that the data is not copied, and any modification to the view will be reflected in the source array:

In [72]:
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


In [73]:
colB[0] = 17

In [74]:
print(B)

[[ 6  5 17  1  1]
 [ 1  0  4  0  1]
 [ 5  9  2  2  9]]


That is, **array slices are mutable**: if they are assigned a new value the original array from which the slice was extracted is modified:

If we omit an index of a $n$-dimensional array it returns, in general, a $(n-1)$-dimensional array:

In [75]:
print(B[1])

[1 0 4 0 1]


For 2D arrays, it is particularly useful remembering that *rows* correspond to the first dimension, and *columns* correspond to the second dimension.

> So far an ndarray looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type?
>
>There are several reasons:
> * Python lists are very general. They can contain *any kind* of object. They are *dynamically typed*. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would *not be very efficient* because of the dynamic typing.
> * Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created. Numpy arrays are **memory efficient**.
>
> Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

### Fancy Indexing

Fancy indexing is the NumPy name for when an integer array or list is used in-place of an index:

In [76]:
a = np.array([n for n in range(5)])
print(a)

[0 1 2 3 4]


In [77]:
row_indices = [3, 1, 2, 3]
print(a[row_indices])

[3 1 2 3]


You can also use negative indices:

In [78]:
row_indices = [-3, -1, -2, -3]
print(a[row_indices])

[2 4 3 2]


Unlike slicing, selecting data from an array by **fancy indexing always creates a copy of the data** in the new array.


### Boolean Indexing

Instead of using integers or arrays/lists of integers to access the element of a NumPy array, we can also use arrays of boolean, called **index masks**. An index masks is a list/array of boolean dat type; when used to index a NumPy array, an element is selected or not depending on the value of the index mask at the position of each element:

In [79]:
a = np.array([n for n in range(5)])
print(a)

[0 1 2 3 4]


In [80]:
index_mask = np.array([True, False, True, False, False])
print(a[index_mask])

[0 2]


In [81]:
# same thing
index_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
print(a[index_mask])

[0 2]


Boolean indexing is very useful to conditionally select elements from an array, using for example comparison operators:

In [82]:
names = np.array(['Alice', 'Bob', 'Bob', 'Charlie', 'Bob', 'David'])
index_mask = names != 'Bob'
print(names[index_mask])

['Alice' 'Charlie' 'David']


It is also possible to mix boolean array using logical conditions. However, the Python keywords `not`, `and` and `or` do not work with boolean arrays. Use `~`, `&` and `|` instead:

In [83]:
print(names[~(names == 'Bob') & (names != 'Alice')])

['Charlie' 'David']


Mixing up boolean indexing and broadcasting allows us many common-sense applications. For example, to set all negative values in an array to 0 we need only to write:

In [84]:
a = np.array([-1, 2, 3, -2, -3, 4, 0])
print(a)

[-1  2  3 -2 -3  4  0]


In [85]:
a[a < 0] = 0
print(a)

[0 2 3 0 0 4 0]


Unlike slicing, selecting data from an array by **boolean indexing always creates a copy of the data** in the new array.

### Copies versus Views

If we want to obtain a copy of the data using slicing too, so that when we get a new completely independent object B copied from A, then we need to do a so-called "**deep copy**" using the function `np.copy`:

In [86]:
a = np.array([1, 2, 3, 4, 5])
b = np.copy(a[:3])

In [87]:
b[:] = 0
print(b)

[0 0 0]


In [88]:
print(a)

[1 2 3 4 5]


## Functions

### Array Functions

There are *many* [array functions](https://docs.scipy.org/doc/numpy/reference/routines.html) we can use to compute with NumPy arrays. The following is a partial list and we'll look closer at mathematical functions in the next section.

| Array Function | Description |
| ---: | :--- |
| `np.sum` | Sum of all the elements in the array. |
| `np.prod` | Product of all the elements in the array.|
| `np.mean` | Arithmetic mean.|
| `np.std`, `np.var` | Standard deviation and variance. |
| `np.min`, `np.max` | Minimum and maximum. |
| `np.argmin`, `np.argmax` | Indices of the minimum and maximum elements. |
| `np.cumsum` | Cumulative sum of elements, starting from 0. |
| `np.cumprod` | Cumulative product of elements, starting from 1. |

Create a 1D NumPy array with random values:

In [89]:
arr = np.array([8, -2, 4, 7, -3])
print(arr)

[ 8 -2  4  7 -3]


Compute the mean of the values in the array:

In [90]:
np.mean(arr)

2.8

Verify the mean once more:

In [91]:
m = np.sum(arr) / arr.size
print(m)

2.8


Find the index of the maximum element in the array:

In [92]:
arr = np.array([8, -2, 4, 7, -3])
max_i = np.argmax(arr)
print(max_i)

0


Verify the maximum value in the array:

In [93]:
np.max(arr)

8

In [94]:
arr[max_i]

8

Array functions apply to 2D arrays as well (and $n$-dimensional arrays in general) with the added feature that we can choose to apply array functions to the entire array, down the columns or across the rows (or any axis).

Create a 2D NumPy array with random values and compute the sum of all the entries:

In [95]:
M = np.array([[2, 4, 2], [2, 1, 1], [3, 2, 0], [0, 6, 2]])
print(M)

[[2 4 2]
 [2 1 1]
 [3 2 0]
 [0 6 2]]


In [96]:
np.sum(M)

25

The function `numpy.sum` also takes a keyword argument `axis` which determines along which dimension to compute the sum:

In [97]:
np.sum(M, axis=0) # Sum of the columns

array([ 7, 13,  5])

In [98]:
np.sum(M, axis=1) # Sum of the rows

array([8, 4, 5, 8])

### Mathematical Functions

[Mathematical functions](http://docs.scipy.org/doc/numpy/reference/routines.math.html) in NumPy are called [**universal functions**](https://docs.scipy.org/doc/numpy/user/quickstart.html#universal-functions) and are *vectorized*. Vectorized functions operate *element-wise* on arrays producing arrays as output and are built to compute values across arrays *very* quickly. 

The following table contains a list of the most important unary ufuncs.

|Function| Description |
|:-------|:---------|
|`np.abs`|Compute the absolute value element-wise for integer, floating-point, or complex values|
|`np.sqrt`|Compute the square root of each element|
|`np.exp`|Compute the exponent $e^x$ of each element|
|`np.log`, `np.log10`, `np.log2`, `np.log1p`|Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively|
|`np.sign`|Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)|
|`np.ceil`|Compute the ceiling of each element|
|`np.floor`|Compute the floor of each element|
|`np.modf`|Return fractional and integral parts of array as a separate array|
|`np.isnan`|Return boolean array indicating whether each value is `NaN` (Not a Number)|
|`np.cos`, `np.cosh`, `np.sin`, `np.sinh`, `np.tan`, `np.tanh`|Regular and hyperbolic trigonometric functions|
|`np.arccos`, `np.arccosh`, `np.arcsin`, `np.arcsinh`, `np.arctan`, `np.arctanh`|Inverse trigonometric functions|

The following table contains a list of the most important binary ufuncs.

|Function| Description |
|:-------|:---------|
|`np.add`|Element-wise addition|
|`np.subtract`|Element-wise subtraction|
|`np.multiply`|Element-wise multiplication|
|`np.divide`|Element-wise division|
|`np.mod`|Element-wise modulus|
|`np.power`|Raise elements in first array to powers indicated in second array |
|`np.maximum`, `np.fmax`|Element-wise maximum; `np.fmax` ignores `NaN`|
|`np.minimum`, `np.fmin`|Element-wise minimum; `np.fmin` ignores `NaN`|

Compute the values $\sin(2 \pi x)$ for $x = 0, 0.25, 0.5, \dots, 1.75$:

In [99]:
x = np.arange(0, 1.25, 0.25)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [100]:
np.sin(2 * np.pi * x)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

We expect the array `[0. 1. 0. -1. 0.]` however there is (as always with floating point numbers) some rounding errors in the result. In numerical computing, we can interpret a number such as $10^{-16}$ as $0$.

Compute the values $\log_{10}(x)$ for $x = 1,10,100,1000,10000$:

In [101]:
x = np.array([1, 10, 100, 1000, 10000])
print(x)

[    1    10   100  1000 10000]


In [102]:
np.log10(x)

array([0., 1., 2., 3., 4.])

Note that we can also evaluate mathematical functions with scalar values:

In [103]:
np.sin(0)

0.0

NumPy also provides familiar mathematical constants such as $\pi$ and $e$:

In [104]:
np.pi

3.141592653589793

In [105]:
np.e

2.718281828459045

For example, verify the limit

$$
\lim_{x \to \infty} \arctan(x) = \frac{\pi}{2}
$$

by evaluating $\arctan(x)$ for some (arbitrary) large value $x$:

In [106]:
np.arctan(10000)

1.5706963267952299

In [107]:
np.pi/2

1.5707963267948966

### Ternary Expressions

The `np.where`function is a vectorized version of the ternary expression `x if <condition> else y`. Suppose we have the following arrays:

In [108]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
y = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
condition = [False, True, False, False, True]

We want to take a value from `x` whenever the corresponding condition in `condition` is `True`, and otherwise take the value from `y`. With `np.where` we can write:

In [109]:
result = np.where(condition, x, y)
print(result)

[0.1 2.  0.3 0.4 5. ]


### Sorting

Like Python's lists, NumPy array can be sorted in-place:

In [110]:
a = [4, 2, 7, 88, -2, 1]
a.sort()
print(a)

[-2, 1, 2, 4, 7, 88]


In [111]:
print(a)

[-2, 1, 2, 4, 7, 88]


Using the function `np.sort` the input array is not modified and a new, sorted array is created:

In [112]:
a = [4, 2, 7, 88, -2, 1]
print(np.sort(a))
print(a)

[-2  1  2  4  7 88]
[4, 2, 7, 88, -2, 1]


### Special Methods for Boolean Arrays

There are two additional methods for boolean arrays:
* `any` to check if at least one value in the array is `True`;
* `all` to test if all values in the array are `True`.

In [113]:
a = np.array([False, False, True, False])
print(a.any())
print(a.all())

True
False


### Set Functions

NumPy has some basic set operations working on 1D arrays only:
* `np.unique` returns the sorted unqiue values in an array;
* `np.in1d` tests membership of the values in one array in another, returning a boolean array.


|Function| Description |
|:-------|:---------|
|`np.unique`|Compute the sorted, unique elements in an array.|
|`np.intersect1d`|Compute the sorted, common elements in two arrays.|
|`np.union1d`|Compute the sorted union elements in two arrays.|
|`np.in1d`|Test membership of the values in one array in another, returning a boolean array.|
|`np.setdiff1d`|Set difference, return elements in and array that are not in the other.|

In [114]:
names = np.array(['Alice', 'Bob', 'Bob', 'Charlie', 'Bob', 'David'])
print(np.unique(names))

['Alice' 'Bob' 'Charlie' 'David']


In [115]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
print(np.in1d(values, [2, 3, 6]))

[ True False False  True  True False  True]


## Reshaping, resizing and stacking

The shape of an Numpy array can be modified **without copying the underlaying data**, i.e., returing a view, which makes it a fast operation even for large arrays:

In [116]:
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [117]:
m, n = M.shape
B = M.reshape((1, n * m))
print(B)

[[1 2 3 4 5 6]]


We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a **copy** of the data:

In [118]:
B = M.flatten()
print(B)

[1 2 3 4 5 6]


## Adding a new dimension

With `np.newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [119]:
v = np.array([1, 2, 3])
print(v.shape)


(3,)


In [120]:
# make a column matrix of the vector v
w = v[:, np.newaxis]
print(w.shape)

(3, 1)


In [121]:
# make a row matrix of the vector v
w = v[np.newaxis, :]
print(w.shape)

(1, 3)


### Stacking

We can build bigger arrays out of smaller arrays by [stacking](https://docs.scipy.org/doc/numpy/user/quickstart.html#stacking-together-different-arrays) along different dimensions using the functions `numpy.hstack` and `numpy.vstack`.

Stack 3 different 1D NumPy arrays of length 3 vertically forming a 3 by 3 matrix:

In [122]:
x = np.array([1, 1, 1])
y = np.array([2, 2, 2])
z = np.array([3, 3, 3])

In [123]:
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


Stack 1D NumPy arrays horizontally to create another 1D array:

In [124]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


Use `np.hstack` and `np.vstack` to build the matrix $T$ where

$$
T = 
\begin{bmatrix}
1 & 1 & 2 & 2 \\ 
1 & 1 & 2 & 2 \\ 
3 & 3 & 4 & 4 \\ 
3 & 3 & 4 & 4
\end{bmatrix}
$$

In [125]:
A = np.ones((2, 2))
B = 2 * np.ones((2, 2))
C = 3 * np.ones((2, 2))
D = 4 * np.ones((2, 2))
A_B = np.hstack((A, B))
print(A_B)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]]


In [126]:
C_D = np.hstack((C, D))
print(C_D)

[[3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [127]:
T = np.vstack((A_B, C_D))
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


## File I/O with Arrays

The `np.save` and `np.load` are the two functions for efficiently saving and loading array data from and to disk. Arrays are saved by default in an uncompressed raw binary format with file extension `.npy`.

In [128]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


If your save filename does not end with `.npy`, the extensions will be automatically added.

In [129]:
np.save('test_a', a)

To correctly load a saved file, the filename **must include the `.npy` extensions**.

In [130]:
b = np.load('test_a.npy')
print(b)

[0 1 2 3 4 5 6 7 8 9]


## Random Number Generators

The subpackage `numpy.random` contains functions to generate NumPy arrays of [random numbers](https://docs.scipy.org/doc/numpy/reference/routines.random.html) sampled from different distributions. The following is a partial list of distributions:

| Function | Description |
| :--- | :--- |
| `numpy.random.rand(d1,...,dn)` | Create a NumPy array (with shape `(d1,...,dn)`) with entries sampled uniformly from `[0,1)` |
| `numpy.random.randn(d1,...,dn)` | Create a NumPy array (with shape `(d1,...,dn)`) with entries sampled from the standard normal distribution |
| `numpy.random.randint(a,b,size)` | Create a NumPy array (with shape `size`) with integer entries from `low` (inclusive) to `high` (exclusive) |

Sample a random number from the [uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_%28continuous%29):

In [131]:
np.random.rand()

0.6584711063945924

Sample 3 random numbers:

In [132]:
np.random.rand(3)

array([0.1135212 , 0.5790922 , 0.53603493])

Create 2D NumPy array of random samples:

In [133]:
np.random.rand(2,4)

array([[0.10372371, 0.99003381, 0.90302009, 0.3193851 ],
       [0.08293488, 0.80402934, 0.74208849, 0.61407595]])

Random samples from the [standard normal distribution](https://en.wikipedia.org/wiki/Normal_distribution):

In [134]:
np.random.randn()

-0.14613974413530106

In [135]:
np.random.randn(3)

array([-0.5368617 ,  0.5607    ,  0.46728486])

In [136]:
np.random.randn(3,1)

array([[ 1.46546945],
       [-0.54656086],
       [-0.29600639]])

Random integers sampled uniformly from various intervals:

In [137]:
np.random.randint(-10,10)

-3

In [138]:
np.random.randint(0,2,(4,8))

array([[0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1]])

In [139]:
np.random.randint(-9,10,(5,2))

array([[ 4,  5],
       [ 6,  3],
       [-2, -6],
       [-2,  8],
       [ 1,  1]])

# Iterating over arrays

In general, **avoid iterating over the elements of arrays whenever possible (at all costs)**. The reason is that in a interpreted language like Python iterations are really slow compared to vectorized operations.


## Exercises (solved)

### Brute Force Optimization

Find the [absolute maximum and minimum](https://en.wikipedia.org/wiki/Maxima_and_minima) values of the function

$$
f(x) = x\sin(x)+\cos(4x)
$$

on the interval $[0,2\pi]$. We know that the maximum and minimum values must occur at either the endpoints $x=0,2\pi$ or at critical points where $f'(x)=0$. However, the derivative is given by

$$
f'(x) = \sin(x) + x \cos(x) - 4\sin(4x)
$$

and the equation $f'(x) = 0$ is impossible to solve explicitly.

Instead, create a 1D NumPy array of $x$ values from $0$ to $2\pi$ of length $N$ (for some arbitrarily large value $N$) and use the functions `numpy.min` and `numpy.max` to find maximum and minimum $y$ values, and the functions `numpy.argmin` and `numpy.argmax` to find the indices of the corresponding $x$ values.

In [140]:
N = 10000
x = np.linspace(0, 2*np.pi, N)
y = x * np.sin(x) + np.cos(4*x)
y_max = np.max(y)
y_min = np.min(y)
x_max = x[np.argmax(y)]
x_min = x[np.argmin(y)]
print('Absolute maximum value is y =', y_max, 'at x =', x_max)
print('Absolute minimum value is y =', y_min, 'at x =', x_min)

Absolute maximum value is y = 2.5992726072887007 at x = 1.628136126702901
Absolute minimum value is y = -5.129752039182 at x = 5.34187001663503


### Riemann Sums

Write a function called `exp_int` which takes input parameters $b$ and $N$ and returns the (left) [Riemann sum](https://en.wikipedia.org/wiki/Riemann_sum)

$$
\int_0^b e^{-x^2} dx \approx \sum_{k=0}^{N-1} e^{-x_k^2} \Delta x
$$

for $\Delta x = b/N$ and the partition $x_k=k \, \Delta x$, $k=0,\dots,N$.

In [141]:
def exp_int(b,N):
    "Compute left Riemann sum of exp(-x^2) from 0 to b with N subintervals."
    x = np.linspace(0,b,N+1)
    x_left_endpoints = x[:-1]
    Delta_x = b/N
    I = Delta_x * np.sum(np.exp(-x_left_endpoints**2))
    return I

The infinite integral satisfies the [beautiful identity](https://en.wikipedia.org/wiki/Gaussian_integral)

$$
\int_0^{\infty} e^{-x^2} dx = \frac{\sqrt{\pi}}{2}
$$

Compute the integral with large values of $b$ and $N$:

In [142]:
exp_int(100,100000)

0.886726925452758

Compare to the true value:

In [143]:
np.pi**0.5/2

0.8862269254527579

### Infinite Products

The cosine function has the following infinite product representation

$$
\cos x = \prod_{k = 1}^{\infty} \left(1 - \frac{4 x^2}{\pi^2 (2k - 1)^2} \right)
$$

Write a function called `cos_product` which takes input parameters $x$ and $N$ and returns the $N$th partial product

$$
\prod_{k = 1}^{N} \left(1 - \frac{4 x^2}{\pi^2 (2k - 1)^2} \right)
$$

In [144]:
def cos_product(x,N):
    "Compute the product \prod_{k=1}^N (1 - 4x^2/(pi^2 (2k - 1)^2)."
    k = np.arange(1,N+1)
    terms = 1 - 4*x**2 / (np.pi**2 * (2*k - 1)**2)
    return np.prod(terms)

Verify our function using values for which we know the result. For example, $\cos(0)=1$, $\cos(\pi)=-1$ and $\cos(\pi/4) = \frac{1}{\sqrt{2}}$.

In [145]:
cos_product(0,10)

1.0

In [146]:
cos_product(np.pi,10000)

-1.0001000050002433

In [147]:
cos_product(np.pi/4,10000000)

0.7071067856245614

In [148]:
1/2**0.5

0.7071067811865475

## Exercises (unsolved)

*  The natural log satisfies the following definite integral

    $$
    \int_1^e \frac{\ln x \ dx}{(1 + \ln x)^2} = \frac{e}{2} - 1
    $$

    Write a function called `log_integral` which takes input parameters $c$ and $N$ and returns the value of the (right) Riemann sum

    $$
    \int_1^c \frac{\ln x \ dx}{(1 + \ln x)^2} \approx \sum_{k=1}^N \frac{\ln x_k \ \Delta x}{(1 + \ln x_k)^2} \ , \ \ \Delta x = \frac{c - 1}{N}
    $$
    
    for the partition $x_k = 1 + k \Delta x$, for $k = 0, \dots , N$.

* Write a function called `k_sum` which takes input parameters `k` and `N` and returns the partial sum

    $$
    \sum_{n=1}^{N} \frac{1}{n^k}
    $$
    
    Verify your function by comparing to the infinite series identity

    $$
    \sum_{n=1}^{\infty} \frac{(-1)^{n+1}}{n^2} = \frac{\pi^2}{12}
    $$

* Write a function called `dot` which takes 3 inputs `M`, `i` and `j` where `M` is a square NumPy array and the function returns the dot product of the $i$th row and the $j$th column of $M$.